# Generated by Django 4.1 on 2022-08-27 16:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10, unique=True, verbose_name='Напрям вітру')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код погоди')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True, verbose_name='Дата і Час спостереження')),
                ('temperature', models.IntegerField(verbose_name='Температура повітря °C')),
                ('velocity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Середня швидкість вітру')),
                ('cloud_amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Кількість хмар')),
                ('visibility_range', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дальність видимості')),
                ('humidity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Відносна вологість повітря')),
                ('atmo_pressure', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Атмосферний тиск')),
                ('lower_cloud_limit', models.IntegerField(verbose_name='Нижня межа хмарності')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.direction')),
                ('weather_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weathercode')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
