# Generated by Django 4.1 on 2022-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='weather_code',
            field=models.CharField(default='CL', max_length=20, verbose_name='Код погоди'),
        ),
        migrations.DeleteModel(
            name='WeatherCode',
        ),
    ]
