# Generated by Django 4.1 on 2023-03-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_cloud_amount_alter_data_lower_cloud_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True, verbose_name='Область')),
                ('datas', models.ManyToManyField(to='main.data')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
