# Generated by Django 4.1 on 2023-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coords',
            field=models.TextField(default='', max_length=1000, verbose_name='Координати мапи'),
        ),
    ]
