# Generated by Django 4.1 on 2023-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_region_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='offset_x',
            field=models.FloatField(default=0, verbose_name='Відступ X'),
        ),
        migrations.AddField(
            model_name='region',
            name='offset_y',
            field=models.FloatField(default=0, verbose_name='Відступ Y'),
        ),
    ]
